server:
  servlet:
    context-path: /v1/user-manager
  port: 8085
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  output:
    ansi.enabled: ALWAYS
  application:
    name: user-manager
  jackson:
    property-naming-strategy: SNAKE_CASE
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/bd_gestor
    username: postgres
    password: prueba
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: manager
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE